### your site title here

title: Hannah Cake
description: PhD Student | University of Kentucky Political Science

baseurl: tinnycat.github.io #name of GitHub repository
url: "" #custom url to be used instead of GitHub repository
email: "hannah.cake@uky.edu" #

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
twitter: "politywithhrc"
linkedin: "hannah-cake-4405bb190"
stackoverflow: 
github: "tinnycat/"
researchgate: 
orcid: 
quora: 
instagram: 
facebook: 


# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  research:
    output: true
    permalink: /research/:name/
    order:
      - shortProject.md
      - longerProjectTitle.md
      - redirect.md
      - project4.md
      - project5.md
      - project6.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
